# Generated by Django 3.2.5 on 2021-10-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main.quiz'),
        ),
    ]
