# Generated by Django 3.2.5 on 2021-10-10 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_quiztaker_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
